package com.asiainfo.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DOWNLOAD_ENTITY".
 */
public class DownloadEntity {

    private Long start_position;
    private Long end_position;
    private Long progress_position;
    private Long download_url;
    private Long thread_id;
    private Long id;

    public DownloadEntity() {
    }

    public DownloadEntity(Long id) {
        this.id = id;
    }

    public DownloadEntity(Long start_position, Long end_position, Long progress_position, Long download_url, Long thread_id, Long id) {
        this.start_position = start_position;
        this.end_position = end_position;
        this.progress_position = progress_position;
        this.download_url = download_url;
        this.thread_id = thread_id;
        this.id = id;
    }

    public Long getStart_position() {
        return start_position;
    }

    public void setStart_position(Long start_position) {
        this.start_position = start_position;
    }

    public Long getEnd_position() {
        return end_position;
    }

    public void setEnd_position(Long end_position) {
        this.end_position = end_position;
    }

    public Long getProgress_position() {
        return progress_position;
    }

    public void setProgress_position(Long progress_position) {
        this.progress_position = progress_position;
    }

    public Long getDownload_url() {
        return download_url;
    }

    public void setDownload_url(Long download_url) {
        this.download_url = download_url;
    }

    public Long getThread_id() {
        return thread_id;
    }

    public void setThread_id(Long thread_id) {
        this.thread_id = thread_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
